name: CI

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prepare environment
      run: |
          npm install
    - name: build
      run: npm run build
