name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prepare environment
      if: github.event.pull_request.merged == true
      run: |
          git config --local user.email "`git show -s --format='%ae' HEAD^2`"
          git config --local user.name "'`git show -s --format='%an' HEAD^2`'"
          npm install
    - name: prepare commit message
      if: github.event.pull_request.merged == true
      run: |
          echo "Update `date --iso-8601=minutes`" > commit_message
          echo "" >> commit_message
          echo "from: [${GITHUB_SHA}](github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})" >> commit_message
          git log --oneline --format=" * %h : %s" $(git merge-base --fork-point master)... >> commit_message
    - name: build
      if: github.event.pull_request.merged == true
      run: npm run build
    - name: deploy demo
      if: github.event.pull_request.merged == true
      env:
          SSH_DIR: ${{ github.workspace }}/.ssh
          GIT_SSH_COMMAND: ssh -i ${{ github.workspace }}/.ssh/id_rsa
      run: |
          git remote add github "git@github.com:${GITHUB_REPOSITORY}.git"
          mkdir "${SSH_DIR}"
          ssh-keyscan -t rsa github.com > "${SSH_DIR}/known_hosts"
          echo "${{secrets.ACTIONS_DEPLOY_KEY}}" > "${SSH_DIR}/id_rsa"
          chmod 400 "${SSH_DIR}/id_rsa"
          git fetch github gh-pages
          git worktree add --track -b gh-pages site github/gh-pages
          npm run build
          cp -r build/* site/
          cd site
          git add -A .
          git commit --file=../commit_message
          git push github gh-pages
          rm -rf ${SSH_DIR}
